#!/usr/bin/with-contenv bash

[[ ! -e /config/sabnzbd.ini ]] && \
  cp /defaults/sabnzbd.ini /config/sabnzbd.ini

[[ ! -e /config/M4V-Converter.conf ]] && \
  cp /mp4/default.conf /config/mp4.conf

[[ -f /config/sabnzbd.ini ]] && \
  source <(cat /config/sabnzbd.ini | grep script_dir | sed 's/\ = \ /=/g') &>/dev/null

[[ -z "${script_dir}" ]] && \
  script_dir=/config/scripts

[[ ! -e "${script_dir}" ]] && \
  mkdir -p "${script_dir}"

FILE="${script_dir}/mp4.sh"
[[ ! -L "${FILE}" ]] && \
  ln -s /mp4/mp4.sh "${FILE}"

chown abc:abc -R \
  /mp4 \
  /config \
  "${script_dir}"
