#!/usr/bin/with-contenv bash

[[ ! -e /config/sabnzbd.ini ]] && \
  cp /defaults/sabnzbd.ini /config/sabnzbd.ini

[[ -f /config/sabnzbd.ini ]] && \
  source <(cat /config/sabnzbd.ini | grep script_dir | sed 's/\ = \ /=/g') &>/dev/null

[[ -z "${script_dir}" ]] && \
  script_dir=/config/scripts

[[ ! -e "${script_dir}" ]] && \
  mkdir -p "${script_dir}"

cp -R /mp4 "${script_dir}"
chown abc:abc -R "${script_dir}"
chmod +x "${script_dir}/mp4/mp4.sh"
