#!/usr/bin/with-contenv bash

[[ ! -e /config/sabnzbd.ini ]] && \
  cp /defaults/sabnzbd.ini /config/sabnzbd.ini

[[ -f /config/sabnzbd.ini ]] && \
  source <(cat /config/sabnzbd.ini | grep script_dir | sed 's/\ = \ /=/g') &>/dev/null

[[ -z "${script_dir}" ]] && \
  script_dir=/config/scripts

mkdir -p "${script_dir}"

cp /mp4.sh "${script_dir}/"
chown abc:abc -R "${script_dir}"
chmod +x "${script_dir}/mp4.sh"
